--
-- V6: widen the user_roles and user_permissions CHECK constraints for the ticketing
-- roles and permissions (TCKET_SCANNER/MANAGER/ADMIN, tcket:scan/manage/admin).
--
-- See the SQLite twin for why this is required at all: both columns are @Enumerated(STRING)
-- with a CHECK listing every legal value, and ddl-auto=validate does not inspect CHECK
-- constraints -- so without this, granting a TCKET_* role fails at INSERT time rather than
-- at startup.
--
-- Postgres can alter constraints in place, so no table rebuild is needed here. The
-- constraints are dropped by discovery rather than by name: V1 declares them inline and
-- unnamed, so their names were generated by the server, and prod's schema predates Flyway
-- (created under ddl-auto=update before the 2026-08-10 cutover) which means its generated
-- names are not guaranteed to match a fresh database's. Dropping whatever CHECK currently
-- constrains the column, then adding an explicitly named replacement, is correct in both
-- cases and leaves the constraint named from here on.
--
-- The SQLite twin of this file must stay at the same version -- see docs/MIGRATIONS.md.

do $$
declare
    constraint_name text;
begin
    for constraint_name in
        select con.conname
        from pg_constraint con
        join pg_class rel on rel.oid = con.conrelid
        where rel.relname = 'user_roles'
          and con.contype = 'c'
    loop
        execute format('alter table user_roles drop constraint %I', constraint_name);
    end loop;

    for constraint_name in
        select con.conname
        from pg_constraint con
        join pg_class rel on rel.oid = con.conrelid
        where rel.relname = 'user_permissions'
          and con.contype = 'c'
    loop
        execute format('alter table user_permissions drop constraint %I', constraint_name);
    end loop;
end $$;

alter table user_roles
    add constraint user_roles_role_check check (role in (
        'USER','ADMIN',
        'BOARD_VIEWER','BOARD_EDITOR','BOARD_ADMIN',
        'TCKET_SCANNER','TCKET_MANAGER','TCKET_ADMIN',
        'ROOT'));

alter table user_permissions
    add constraint user_permissions_permission_check check (permission in (
        'MEDIA_UPLOAD_SELF','MEDIA_UPLOAD_MODERATE','MEDIA_UPLOAD_READ','MEDIA_EVENT_WRITE',
        'BOARD_CONTENT_READ','BOARD_POSTER_WRITE','BOARD_EVENT_WRITE','BOARD_SOCIAL_WRITE',
        'BOARD_WEEKLY_WRITE','BOARD_TICKER_WRITE',
        'BOARD_CONFIG_READ','BOARD_CONFIG_WRITE','BOARD_REFRESH',
        'BOARD_DEVICE_READ','BOARD_DEVICE_ENROLL','BOARD_DEVICE_REVOKE','BOARD_TELEMETRY_SUBSCRIBE',
        'BOARD_COMMAND_BENIGN','BOARD_COMMAND_DISRUPTIVE','BOARD_COMMAND_INSPECT',
        'TCKET_SCAN','TCKET_MANAGE','TCKET_ADMIN',
        'IAM_USER_READ','IAM_USER_WRITE','IAM_ROLE_GRANT','AUDIT_READ'));
